name: "NPDS Patch After Sync"
on:
  workflow_call:
  workflow_dispatch:
jobs:
  apply-npds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout FluentUI code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Clone NPDS repo from Azure DevOps
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: |
          git clone https://:$AZURE_DEVOPS_PAT@dev.azure.com/nbsdev/NBS%20Product%20Design/_git/DesignSystem npds-repo

      - name: Verify files exist before copying
        run: |
          echo "Checking NPDS file exists..."
          if [ ! -f "npds-repo/packages/npds-components/src/components/button/button.styles.ts" ]; then
            echo "NPDS button styles not found!"
            echo "Available files in npds-repo:"
            find npds-repo -name "*.styles.ts" | head -10
            exit 1
          fi

          echo "Checking FluentUI target file exists..."
          if [ ! -f "packages/web-components/src/button/button.styles.ts" ]; then
            echo "FluentUI button styles not found!"
            exit 1
          fi

          echo "Both files found, proceeding with copy..."

      - name: Copy NPDS styles and patch Fluent button
        run: |
          # Copy the NPDS button styles
          cp npds-repo/packages/npds-components/src/components/button/button.styles.ts ./npds-button-styles.ts

          # Patch Fluent's button.styles.ts
          FILE="packages/web-components/src/button/button.styles.ts"
          grep -q "npdsButtonStyles" $FILE || \
            sed -i '1iimport { buttonStyles as npdsButtonStyles } from "./npds-button-styles";' $FILE
          sed -i 's/export const styles = css/export const originalButtonStyles = css/' $FILE
          cat << 'EOF' >> $FILE
          // ── NPDS OVERRIDE LAYER ──
          export const styles = css`
            ${originalButtonStyles}
            ${npdsButtonStyles}
          `;
          // ────────────────────────
          EOF

          # Clean up
          rm -rf npds-repo

      - name: Commit and push NPDS patch
        env:
          GH_PAT: ${{ secrets.FLUENTUI_ACTION }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet -- packages/web-components/src/button/button.styles.ts; then
            git add packages/web-components/src/button/button.styles.ts npds-button-styles.ts
            git commit -m "chore: layer NPDS button styles"
            git push https://$GH_PAT@github.com/${GITHUB_REPOSITORY}.git main
          else
            echo "No NPDS changes needed."
          fi
