name: Sync Fork with Upstream
on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    outputs:
      changes_made: ${{ steps.check-changes.outputs.changes_made }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
          token: ${{ secrets.FLUENTUI_ACTION }}
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/microsoft/fluentui.git
          git remote -v
      - name: Fetch from upstream
        run: |
          git fetch upstream master
          git fetch origin main
      - name: Ensure on main branch
        run: |
          git checkout main
          git branch -v
      - name: Check for conflicts
        id: check-conflicts
        run: |
          git checkout -b temp-merge-branch main
          if git merge upstream/master --no-commit --no-ff; then
            # No merge conflicts
            echo "has_conflicts=false" >> $GITHUB_OUTPUT
            echo "No merge conflicts detected."
            git merge --abort || true  # Clean up
          else
            # Merge conflicts
            echo "has_conflicts=true" >> $GITHUB_OUTPUT
            echo "Merge conflicts detected."
            git merge --abort || true
          fi
          git checkout main
          git branch -D temp-merge-branch
      - name: Set date
        id: date
        run: echo "date=$(date +%Y%m%d)" >> $GITHUB_OUTPUT
      - name: Check if there are changes to merge
        id: check-changes
        run: |
          # Check if there are any differences between main and upstream/master
          if git diff --quiet main upstream/master; then
            echo "changes_made=false" >> $GITHUB_OUTPUT
            echo "No changes detected between main and upstream/master"
          else
            echo "changes_made=true" >> $GITHUB_OUTPUT
            echo "Changes detected between main and upstream/master"
          fi
      - name: Direct merge if no conflicts
        if: steps.check-conflicts.outputs.has_conflicts == 'false' && steps.check-changes.outputs.changes_made == 'true'
        run: |
          git merge upstream/master --no-edit
          echo "Merged upstream/master into origin/main"
      - name: Push directly if no conflicts
        if: steps.check-conflicts.outputs.has_conflicts == 'false' && steps.check-changes.outputs.changes_made == 'true'
        env:
          GH_PAT: ${{ secrets.FLUENTUI_ACTION }}
        run: |
          git push https://$GH_PAT@github.com/${GITHUB_REPOSITORY}.git main


  # New job to trigger NPDS patch workflow
  trigger-npds-patch:
    needs: sync
    if: needs.sync.outputs.changes_made == 'true' && needs.sync.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger NPDS Patch Workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.FLUENTUI_ACTION }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'npds-patch.yml',
              ref: 'main'
            });
            console.log('NPDS Patch workflow triggered successfully');
